name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: [main, master]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # ğŸ™‹ Introduction
      - name: Introduction
        uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics/metrics.plugin.introduction.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_introduction: yes
          plugin_introduction_title: yes

      # ğŸ“… Isometric commit calendar (full year)
      - name: Isometric Calendar
        uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics/metrics.plugin.isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

      # ğŸˆ·ï¸ Languages activity (Indepth analysis)
      - name: Languages Activity
        uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics/metrics.plugin.languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_limit: 8
          plugin_languages_analysis_timeout: 15

      # ğŸŒ¸ Anilist - Favorite Anime
      - name: Anilist Favorite Anime
        uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics/metrics.plugin.anilist.anime.svg
          token: NOT_NEEDED
          base: ""
          plugin_anilist: yes
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites
          plugin_anilist_limit: 2
          plugin_anilist_user: melekbadreddine

      # ğŸŒ¸ Anilist - Favorite Manga
      - name: Anilist Favorite Manga
        uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics/metrics.plugin.anilist.manga.svg
          token: NOT_NEEDED
          base: ""
          plugin_anilist: yes
          plugin_anilist_medias: manga
          plugin_anilist_sections: favorites
          plugin_anilist_limit: 2
          plugin_anilist_user: melekbadreddine

      # ğŸŒ¸ Anilist - Favorite Characters
      - name: Anilist Favorite Characters
        uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics/metrics.plugin.anilist.characters.svg
          token: NOT_NEEDED
          base: ""
          plugin_anilist: yes
          plugin_anilist_medias: characters
          plugin_anilist_sections: favorites
          plugin_anilist_limit: 22
          plugin_anilist_user: melekbadreddine
